### ISSUE TITLE
Deprecation of Mojo::Util::slurp

### ISSUE THREAD

**Issue by plk** [jhthorsen/mojolicious-plugin-openapi#23]
With latest Mojolicious:

Mojo::Util::slurp is DEPRECATED in favor of Mojo::File::slurp at /usr/local/informatica/perl/lib/site_perl/5.24.0/Mojolicious/Plugin/OpenAPI.pm line 133.

**Comment by jhthorsen** [comment]
Which version is this? Pretty sure this is fixed in 1.07.

Please re-open if I'm wrong.

**Comment by plk** [comment]
Still happens with 1.08 and Mojolicious 7.23. It started when I upgraded to 1.08 7.23.
